spring:
    application:
        name: dashboardapp

spring.jmx:
   enabled: false
   
spring.data:
  rest:
    base-path: /api

spring.datasource:
    url: jdbc:mysql://localhost:3306/oauth?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: oauth
    password: oauth
    driver-class-name: com.mysql.jdbc.Driver
spring.jpa:
        database: MYSQL
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop #validate#create-drop#create
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate.naming.strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy   # Naming strategy fully qualified name.
        show-sql: true # Enable logging of SQL statements.
        open-in-view: true # Register OpenEntityManagerInViewInterceptor. Binds a JPA EntityManager to the thread for the entire processing of the request.
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            #hibernate.hbm2ddl.auto: create-drop
spring.jackson:
    date-format: yyyy-MM-dd HH:mm:ss # Date format string or a fully-qualified date format class name. For instance `yyyy-MM-dd HH:mm:ss`.
    joda-date-time-format: yyyy-MM-dd# Joda date time format string. If not configured, "date-format" will be used as a fallback if it is configured with a format string.
    locale: en_US # Locale used for formatting.
    time-zone: America/Los_Angeles # Time zone used when formatting dates. For instance `America/Los_Angeles`
    
spring.http:
      encoding:
        charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly.
        enabled: true # Enable http encoding support.
        force: true # Force the encoding to the configured charset on HTTP requests and responses.
      converters:
        preferred-json-mapper: jackson

spring.mail:
    default-encoding: UTF-8
    host: localhost
    protocol: smtp
    username: 
    password: 
    port: 25
    test-connection: false

spring.freemarker:
      cache: false # Enable template caching.
      charset: UTF-8 # Template encoding.
      check-template-location: true # Check that the templates location exists.
      content-type: text/html # Content-Type value.
      enabled: true # Enable MVC view resolution for this technology.
      expose-request-attributes: false # Set whether all request attributes should be added to the model prior to merging with the template.
      expose-session-attributes: false # Set whether all HttpSession attributes should be added to the model prior to merging with the template.
      expose-spring-macro-helpers: true # Set whether to expose a RequestContext for use by Spring's macro library, under the name "springMacroRequestContext".
      prefer-file-system-access: true # Prefer file system access for template loading. File system access enables hot detection of template changes.
      prefix:  # Prefix that gets prepended to view names when building a URL.
      request-context-attribute:  # Name of the RequestContext attribute for all views.
      suffix: .ftl # Suffix that gets appended to view names when building a URL.
      template-loader-path: classpath:/templates # Comma-separated list of template paths.
      view-names:  # White list of view names that can be resolved.

 
server:
#  context-path: /api
#  compression.enabled: false
#  display-name: api
  port: 8080
  compression:
     enabled: true
     mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
     min-response-size: 1024


multipart:
  enabled: true # Enable support of multi-part uploads.
  file-size-threshold: 0 # Threshold after which files will be written to disk. Values can use the suffixed "MB" or "KB" to indicate a Megabyte or Kilobyte size.
  location:  # Intermediate location of uploaded files.
  max-file-size: 1Mb # Max file size. Values can use the suffixed "MB" or "KB" to indicate a Megabyte or Kilobyte size.
  max-request-size: 10Mb # Max request size. Values can use the suffixed "MB" or "KB" to indicate a Megabyte or Kilobyte size.

security:
    basic:
        enabled: false

management:
  port: 8082

spring.cache.jcache.config: ehcache3.xml


#security.user.name: greg
#security.user.password: turnquist
#security.oauth2.client.client-id: foo
#security.oauth2.client.client-secret: bar
#security.oauth2.authorization.checkTokenAccess: isAuthenticated()

authentication.oauth.clientid: clientapp
authentication.oauth.secret: 123456

logging.level.org.springframework.security: DEBUG
logging.level.org.springframework.boot.actuate.audit.listener.AuditListener: DEBUG

project:
  name: dashboard
  version: 1.0
  description: dashboard default description
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}



app:
    security:
        rememberMe:
            # security key (this key should be unique for your application, and kept secret)
            key: e48612ba1fd46fa7089fe9f5085d8d164b53ffb2
    swagger:
        title: dashboard API
        description: dashboard API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contactName: ohmylove99
        contactUrl:
        contactEmail:
        license:
        licenseUrl:
    cors: #By default CORS are not enabled. Uncomment to enable.
        allowed-origins: "*"
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        allowed-headers: "*"
        exposed-headers:
        allow-credentials: true
        max-age: 1800

---
spring:
  profiles: test

spring.jpa:
    hibernate.ddl-auto: create-drop

